/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvatarColorChoice {
  'colorType' : AvatarColorType,
  'colorId' : bigint,
}
export type AvatarColorType = { 'skinToneLevel' : null } |
  { 'clothingColor' : null } |
  { 'hairColor' : null };
export interface AvatarCustomization {
  'clothing' : [] | [AvatarStyleChoice],
  'eyewear' : [] | [AvatarStyleChoice],
  'skinTone' : AvatarColorChoice,
  'hairType' : AvatarStyleChoice,
}
export interface AvatarStyleChoice {
  'id' : bigint,
  'styleType' : AvatarStyleType,
}
export type AvatarStyleType = { 'hat' : null } |
  { 'wig' : null } |
  { 'glasses' : null } |
  { 'cape' : null } |
  { 'hair' : null } |
  { 'shirt' : null } |
  { 'beard' : null };
export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
  'conversationType' : ConversationType,
}
export type ConversationType = { 'group' : null } |
  { 'direct' : null };
export type DebateStyle = { 'aggressive' : null } |
  { 'creative' : null } |
  { 'civil' : null } |
  { 'random' : null };
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface ModerationAction {
  'id' : bigint,
  'moderator' : Principal,
  'userId' : Principal,
  'actionType' : ModerationType,
  'description' : string,
  'timestamp' : Time,
  'violationType' : ViolationType,
}
export type ModerationType = { 'ban' : null } |
  { 'warning' : null } |
  { 'strike' : null };
export interface Post {
  'id' : bigint,
  'media' : [] | [ExternalBlob],
  'content' : string,
  'section' : SectionType,
  'author' : Principal,
  'likes' : Array<Principal>,
  'pinned' : boolean,
  'timestamp' : Time,
  'replies' : Array<Reply>,
}
export interface Reply {
  'id' : bigint,
  'parentPostId' : bigint,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
}
export interface Report {
  'id' : bigint,
  'status' : ReportStatus,
  'reportedContent' : ReportedContent,
  'description' : string,
  'timestamp' : Time,
  'reporter' : Principal,
  'violationType' : ViolationType,
}
export type ReportStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'reviewed' : null };
export type ReportedContent = { 'post' : bigint } |
  { 'userProfile' : Principal } |
  { 'reply' : bigint };
export type SectionType = { 'randomDebates' : null } |
  { 'civilDebate' : null } |
  { 'quotesPoems' : null } |
  { 'aggressiveDebate' : null };
export interface SocialMediaLinks {
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'pinterest' : [] | [string],
  'facebook' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'username' : string,
  'interests' : Array<string>,
  'socialMedia' : [] | [SocialMediaLinks],
  'debateStyle' : DebateStyle,
  'avatar' : AvatarCustomization,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ViolationType = { 'other' : null } |
  { 'spam' : null } |
  { 'harassment' : null } |
  { 'inappropriateContent' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReply' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], SectionType],
    undefined
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followTopic' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[bigint], [] | [Conversation]>,
  'getFollowedTopics' : ActorMethod<[], Array<string>>,
  'getFollowing' : ActorMethod<[], Array<Principal>>,
  'getModerationActions' : ActorMethod<[Principal], Array<ModerationAction>>,
  'getMyConversations' : ActorMethod<[], Array<Conversation>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'moderateUser' : ActorMethod<
    [Principal, ModerationType, ViolationType, string],
    undefined
  >,
  'pinPost' : ActorMethod<[bigint], undefined>,
  'reportContent' : ActorMethod<
    [ReportedContent, ViolationType, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'startConversation' : ActorMethod<
    [Array<Principal>, ConversationType],
    bigint
  >,
  'unfollowTopic' : ActorMethod<[string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unpinPost' : ActorMethod<[bigint], undefined>,
  'updateReportStatus' : ActorMethod<[bigint, ReportStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];