/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SectionType = IDL.Variant({
  'randomDebates' : IDL.Null,
  'civilDebate' : IDL.Null,
  'quotesPoems' : IDL.Null,
  'aggressiveDebate' : IDL.Null,
});
export const SocialMediaLinks = IDL.Record({
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'pinterest' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
});
export const DebateStyle = IDL.Variant({
  'aggressive' : IDL.Null,
  'creative' : IDL.Null,
  'civil' : IDL.Null,
  'random' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'socialMedia' : IDL.Opt(SocialMediaLinks),
  'debateStyle' : DebateStyle,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const ConversationType = IDL.Variant({
  'group' : IDL.Null,
  'direct' : IDL.Null,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
  'conversationType' : ConversationType,
});
export const ModerationType = IDL.Variant({
  'ban' : IDL.Null,
  'warning' : IDL.Null,
  'strike' : IDL.Null,
});
export const ViolationType = IDL.Variant({
  'other' : IDL.Null,
  'spam' : IDL.Null,
  'harassment' : IDL.Null,
  'inappropriateContent' : IDL.Null,
});
export const ModerationAction = IDL.Record({
  'id' : IDL.Nat,
  'moderator' : IDL.Principal,
  'userId' : IDL.Principal,
  'actionType' : ModerationType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'violationType' : ViolationType,
});
export const Reply = IDL.Record({
  'id' : IDL.Nat,
  'parentPostId' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(ExternalBlob),
  'content' : IDL.Text,
  'section' : SectionType,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'pinned' : IDL.Bool,
  'timestamp' : Time,
  'replies' : IDL.Vec(Reply),
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const ReportedContent = IDL.Variant({
  'post' : IDL.Nat,
  'userProfile' : IDL.Principal,
  'reply' : IDL.Nat,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReportStatus,
  'reportedContent' : ReportedContent,
  'description' : IDL.Text,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'violationType' : ViolationType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), SectionType],
      [],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'findUserIdByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'followTopic' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
  'getFollowedTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getModerationActions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ModerationAction)],
      ['query'],
    ),
  'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'moderateUser' : IDL.Func(
      [IDL.Principal, ModerationType, ViolationType, IDL.Text],
      [],
      [],
    ),
  'pinPost' : IDL.Func([IDL.Nat], [], []),
  'reportContent' : IDL.Func(
      [ReportedContent, ViolationType, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'startConversation' : IDL.Func(
      [IDL.Vec(IDL.Principal), ConversationType],
      [IDL.Nat],
      [],
    ),
  'unfollowTopic' : IDL.Func([IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unpinPost' : IDL.Func([IDL.Nat], [], []),
  'updateReportStatus' : IDL.Func([IDL.Nat, ReportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SectionType = IDL.Variant({
    'randomDebates' : IDL.Null,
    'civilDebate' : IDL.Null,
    'quotesPoems' : IDL.Null,
    'aggressiveDebate' : IDL.Null,
  });
  const SocialMediaLinks = IDL.Record({
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'pinterest' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
  });
  const DebateStyle = IDL.Variant({
    'aggressive' : IDL.Null,
    'creative' : IDL.Null,
    'civil' : IDL.Null,
    'random' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'socialMedia' : IDL.Opt(SocialMediaLinks),
    'debateStyle' : DebateStyle,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const ConversationType = IDL.Variant({
    'group' : IDL.Null,
    'direct' : IDL.Null,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
    'conversationType' : ConversationType,
  });
  const ModerationType = IDL.Variant({
    'ban' : IDL.Null,
    'warning' : IDL.Null,
    'strike' : IDL.Null,
  });
  const ViolationType = IDL.Variant({
    'other' : IDL.Null,
    'spam' : IDL.Null,
    'harassment' : IDL.Null,
    'inappropriateContent' : IDL.Null,
  });
  const ModerationAction = IDL.Record({
    'id' : IDL.Nat,
    'moderator' : IDL.Principal,
    'userId' : IDL.Principal,
    'actionType' : ModerationType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'violationType' : ViolationType,
  });
  const Reply = IDL.Record({
    'id' : IDL.Nat,
    'parentPostId' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(ExternalBlob),
    'content' : IDL.Text,
    'section' : SectionType,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'pinned' : IDL.Bool,
    'timestamp' : Time,
    'replies' : IDL.Vec(Reply),
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const ReportedContent = IDL.Variant({
    'post' : IDL.Nat,
    'userProfile' : IDL.Principal,
    'reply' : IDL.Nat,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReportStatus,
    'reportedContent' : ReportedContent,
    'description' : IDL.Text,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'violationType' : ViolationType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), SectionType],
        [],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'findUserIdByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'followTopic' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
    'getFollowedTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getModerationActions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ModerationAction)],
        ['query'],
      ),
    'getMyConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'moderateUser' : IDL.Func(
        [IDL.Principal, ModerationType, ViolationType, IDL.Text],
        [],
        [],
      ),
    'pinPost' : IDL.Func([IDL.Nat], [], []),
    'reportContent' : IDL.Func(
        [ReportedContent, ViolationType, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'startConversation' : IDL.Func(
        [IDL.Vec(IDL.Principal), ConversationType],
        [IDL.Nat],
        [],
      ),
    'unfollowTopic' : IDL.Func([IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unpinPost' : IDL.Func([IDL.Nat], [], []),
    'updateReportStatus' : IDL.Func([IDL.Nat, ReportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };