/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Conversation {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<Message>;
    conversationType: ConversationType;
}
export interface Reply {
    id: bigint;
    parentPostId: bigint;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
}
export type Time = bigint;
export type ReportedContent = {
    __kind__: "post";
    post: bigint;
} | {
    __kind__: "userProfile";
    userProfile: Principal;
} | {
    __kind__: "reply";
    reply: bigint;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SocialMediaLinks {
    twitter?: string;
    instagram?: string;
    pinterest?: string;
    facebook?: string;
}
export interface AvatarStyleChoice {
    id: bigint;
    styleType: AvatarStyleType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: bigint;
    status: ReportStatus;
    reportedContent: ReportedContent;
    description: string;
    timestamp: Time;
    reporter: Principal;
    violationType: ViolationType;
}
export interface AvatarCustomization {
    clothing?: AvatarStyleChoice;
    eyewear?: AvatarStyleChoice;
    skinTone: AvatarColorChoice;
    hairType: AvatarStyleChoice;
}
export interface ModerationAction {
    id: bigint;
    moderator: Principal;
    userId: Principal;
    actionType: ModerationType;
    description: string;
    timestamp: Time;
    violationType: ViolationType;
}
export interface AvatarColorChoice {
    colorType: AvatarColorType;
    colorId: bigint;
}
export interface Post {
    id: bigint;
    media?: ExternalBlob;
    content: string;
    section: SectionType;
    author: Principal;
    likes: Array<Principal>;
    pinned: boolean;
    timestamp: Time;
    replies: Array<Reply>;
}
export interface Message {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    id: Principal;
    username: string;
    interests: Array<string>;
    socialMedia?: SocialMediaLinks;
    debateStyle: DebateStyle;
    avatar: AvatarCustomization;
}
export enum AvatarColorType {
    skinToneLevel = "skinToneLevel",
    clothingColor = "clothingColor",
    hairColor = "hairColor"
}
export enum AvatarStyleType {
    hat = "hat",
    wig = "wig",
    glasses = "glasses",
    cape = "cape",
    hair = "hair",
    shirt = "shirt",
    beard = "beard"
}
export enum ConversationType {
    group = "group",
    direct = "direct"
}
export enum DebateStyle {
    aggressive = "aggressive",
    creative = "creative",
    civil = "civil",
    random = "random"
}
export enum ModerationType {
    ban = "ban",
    warning = "warning",
    strike = "strike"
}
export enum ReportStatus {
    resolved = "resolved",
    pending = "pending",
    reviewed = "reviewed"
}
export enum SectionType {
    randomDebates = "randomDebates",
    civilDebate = "civilDebate",
    quotesPoems = "quotesPoems",
    aggressiveDebate = "aggressiveDebate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum ViolationType {
    other = "other",
    spam = "spam",
    harassment = "harassment",
    inappropriateContent = "inappropriateContent"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReply(postId: bigint, content: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(content: string, media: ExternalBlob | null, section: SectionType): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    followTopic(topic: string): Promise<void>;
    followUser(userId: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(conversationId: bigint): Promise<Conversation | null>;
    getFollowedTopics(): Promise<Array<string>>;
    getFollowing(): Promise<Array<Principal>>;
    getModerationActions(userId: Principal): Promise<Array<ModerationAction>>;
    getMyConversations(): Promise<Array<Conversation>>;
    getPost(postId: bigint): Promise<Post | null>;
    getPosts(): Promise<Array<Post>>;
    getReports(): Promise<Array<Report>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    moderateUser(userId: Principal, actionType: ModerationType, violationType: ViolationType, description: string): Promise<void>;
    pinPost(postId: bigint): Promise<void>;
    reportContent(reportedContent: ReportedContent, violationType: ViolationType, description: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(conversationId: bigint, content: string): Promise<void>;
    startConversation(participants: Array<Principal>, convType: ConversationType): Promise<bigint>;
    unfollowTopic(topic: string): Promise<void>;
    unfollowUser(userId: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    unpinPost(postId: bigint): Promise<void>;
    updateReportStatus(reportId: bigint, status: ReportStatus): Promise<void>;
}
import type { AvatarColorChoice as _AvatarColorChoice, AvatarColorType as _AvatarColorType, AvatarCustomization as _AvatarCustomization, AvatarStyleChoice as _AvatarStyleChoice, AvatarStyleType as _AvatarStyleType, Conversation as _Conversation, ConversationType as _ConversationType, DebateStyle as _DebateStyle, ExternalBlob as _ExternalBlob, Message as _Message, ModerationAction as _ModerationAction, ModerationType as _ModerationType, Post as _Post, Reply as _Reply, Report as _Report, ReportStatus as _ReportStatus, ReportedContent as _ReportedContent, SectionType as _SectionType, SocialMediaLinks as _SocialMediaLinks, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, ViolationType as _ViolationType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReply(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: string, arg1: ExternalBlob | null, arg2: SectionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_SectionType_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_SectionType_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followTopic(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: bigint): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowedTopics(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowedTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowedTopics();
            return result;
        }
    }
    async getFollowing(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing();
            return result;
        }
    }
    async getModerationActions(arg0: Principal): Promise<Array<ModerationAction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationActions(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationActions(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConversations();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConversations();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async moderateUser(arg0: Principal, arg1: ModerationType, arg2: ViolationType, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderateUser(arg0, to_candid_ModerationType_n64(this._uploadFile, this._downloadFile, arg1), to_candid_ViolationType_n66(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderateUser(arg0, to_candid_ModerationType_n64(this._uploadFile, this._downloadFile, arg1), to_candid_ViolationType_n66(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async pinPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinPost(arg0);
            return result;
        }
    }
    async reportContent(arg0: ReportedContent, arg1: ViolationType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportContent(to_candid_ReportedContent_n68(this._uploadFile, this._downloadFile, arg0), to_candid_ViolationType_n66(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportContent(to_candid_ReportedContent_n68(this._uploadFile, this._downloadFile, arg0), to_candid_ViolationType_n66(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startConversation(arg0: Array<Principal>, arg1: ConversationType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0, to_candid_ConversationType_n86(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0, to_candid_ConversationType_n86(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unfollowTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowTopic(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unpinPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinPost(arg0);
            return result;
        }
    }
    async updateReportStatus(arg0: bigint, arg1: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n88(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n88(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AvatarColorChoice_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarColorChoice): AvatarColorChoice {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarColorType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarColorType): AvatarColorType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarCustomization_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarCustomization): AvatarCustomization {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarStyleChoice_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarStyleChoice): AvatarStyleChoice {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_AvatarStyleType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarStyleType): AvatarStyleType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationType): ConversationType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_DebateStyle_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebateStyle): DebateStyle {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ModerationAction_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationAction): ModerationAction {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationType): ModerationType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ReportedContent_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportedContent): ReportedContent {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_SectionType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionType): SectionType {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaLinks_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaLinks): SocialMediaLinks {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ViolationType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ViolationType): ViolationType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocialMediaLinks]): SocialMediaLinks | null {
    return value.length === 0 ? null : from_candid_SocialMediaLinks_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvatarStyleChoice]): AvatarStyleChoice | null {
    return value.length === 0 ? null : from_candid_AvatarStyleChoice_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : from_candid_Conversation_n37(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n50(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    username: string;
    interests: Array<string>;
    socialMedia: [] | [_SocialMediaLinks];
    debateStyle: _DebateStyle;
    avatar: _AvatarCustomization;
}): {
    id: Principal;
    username: string;
    interests: Array<string>;
    socialMedia?: SocialMediaLinks;
    debateStyle: DebateStyle;
    avatar: AvatarCustomization;
} {
    return {
        id: value.id,
        username: value.username,
        interests: value.interests,
        socialMedia: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.socialMedia)),
        debateStyle: from_candid_DebateStyle_n21(_uploadFile, _downloadFile, value.debateStyle),
        avatar: from_candid_AvatarCustomization_n23(_uploadFile, _downloadFile, value.avatar)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitter: [] | [string];
    instagram: [] | [string];
    pinterest: [] | [string];
    facebook: [] | [string];
}): {
    twitter?: string;
    instagram?: string;
    pinterest?: string;
    facebook?: string;
} {
    return {
        twitter: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.twitter)),
        instagram: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.instagram)),
        pinterest: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.pinterest)),
        facebook: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.facebook))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: [] | [_AvatarStyleChoice];
    eyewear: [] | [_AvatarStyleChoice];
    skinTone: _AvatarColorChoice;
    hairType: _AvatarStyleChoice;
}): {
    clothing?: AvatarStyleChoice;
    eyewear?: AvatarStyleChoice;
    skinTone: AvatarColorChoice;
    hairType: AvatarStyleChoice;
} {
    return {
        clothing: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.clothing)),
        eyewear: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.eyewear)),
        skinTone: from_candid_AvatarColorChoice_n30(_uploadFile, _downloadFile, value.skinTone),
        hairType: from_candid_AvatarStyleChoice_n26(_uploadFile, _downloadFile, value.hairType)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    styleType: _AvatarStyleType;
}): {
    id: bigint;
    styleType: AvatarStyleType;
} {
    return {
        id: value.id,
        styleType: from_candid_AvatarStyleType_n28(_uploadFile, _downloadFile, value.styleType)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorType: _AvatarColorType;
    colorId: bigint;
}): {
    colorType: AvatarColorType;
    colorId: bigint;
} {
    return {
        colorType: from_candid_AvatarColorType_n32(_uploadFile, _downloadFile, value.colorType),
        colorId: value.colorId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<_Message>;
    conversationType: _ConversationType;
}): {
    id: bigint;
    participants: Array<Principal>;
    messages: Array<Message>;
    conversationType: ConversationType;
} {
    return {
        id: value.id,
        participants: value.participants,
        messages: value.messages,
        conversationType: from_candid_ConversationType_n39(_uploadFile, _downloadFile, value.conversationType)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    moderator: Principal;
    userId: Principal;
    actionType: _ModerationType;
    description: string;
    timestamp: _Time;
    violationType: _ViolationType;
}): {
    id: bigint;
    moderator: Principal;
    userId: Principal;
    actionType: ModerationType;
    description: string;
    timestamp: Time;
    violationType: ViolationType;
} {
    return {
        id: value.id,
        moderator: value.moderator,
        userId: value.userId,
        actionType: from_candid_ModerationType_n44(_uploadFile, _downloadFile, value.actionType),
        description: value.description,
        timestamp: value.timestamp,
        violationType: from_candid_ViolationType_n46(_uploadFile, _downloadFile, value.violationType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    media: [] | [_ExternalBlob];
    content: string;
    section: _SectionType;
    author: Principal;
    likes: Array<Principal>;
    pinned: boolean;
    timestamp: _Time;
    replies: Array<_Reply>;
}): Promise<{
    id: bigint;
    media?: ExternalBlob;
    content: string;
    section: SectionType;
    author: Principal;
    likes: Array<Principal>;
    pinned: boolean;
    timestamp: Time;
    replies: Array<Reply>;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n52(_uploadFile, _downloadFile, value.media)),
        content: value.content,
        section: from_candid_SectionType_n54(_uploadFile, _downloadFile, value.section),
        author: value.author,
        likes: value.likes,
        pinned: value.pinned,
        timestamp: value.timestamp,
        replies: value.replies
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReportStatus;
    reportedContent: _ReportedContent;
    description: string;
    timestamp: _Time;
    reporter: Principal;
    violationType: _ViolationType;
}): {
    id: bigint;
    status: ReportStatus;
    reportedContent: ReportedContent;
    description: string;
    timestamp: Time;
    reporter: Principal;
    violationType: ViolationType;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n60(_uploadFile, _downloadFile, value.status),
        reportedContent: from_candid_ReportedContent_n62(_uploadFile, _downloadFile, value.reportedContent),
        description: value.description,
        timestamp: value.timestamp,
        reporter: value.reporter,
        violationType: from_candid_ViolationType_n46(_uploadFile, _downloadFile, value.violationType)
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aggressive: null;
} | {
    creative: null;
} | {
    civil: null;
} | {
    random: null;
}): DebateStyle {
    return "aggressive" in value ? DebateStyle.aggressive : "creative" in value ? DebateStyle.creative : "civil" in value ? DebateStyle.civil : "random" in value ? DebateStyle.random : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hat: null;
} | {
    wig: null;
} | {
    glasses: null;
} | {
    cape: null;
} | {
    hair: null;
} | {
    shirt: null;
} | {
    beard: null;
}): AvatarStyleType {
    return "hat" in value ? AvatarStyleType.hat : "wig" in value ? AvatarStyleType.wig : "glasses" in value ? AvatarStyleType.glasses : "cape" in value ? AvatarStyleType.cape : "hair" in value ? AvatarStyleType.hair : "shirt" in value ? AvatarStyleType.shirt : "beard" in value ? AvatarStyleType.beard : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skinToneLevel: null;
} | {
    clothingColor: null;
} | {
    hairColor: null;
}): AvatarColorType {
    return "skinToneLevel" in value ? AvatarColorType.skinToneLevel : "clothingColor" in value ? AvatarColorType.clothingColor : "hairColor" in value ? AvatarColorType.hairColor : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    group: null;
} | {
    direct: null;
}): ConversationType {
    return "group" in value ? ConversationType.group : "direct" in value ? ConversationType.direct : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ban: null;
} | {
    warning: null;
} | {
    strike: null;
}): ModerationType {
    return "ban" in value ? ModerationType.ban : "warning" in value ? ModerationType.warning : "strike" in value ? ModerationType.strike : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    spam: null;
} | {
    harassment: null;
} | {
    inappropriateContent: null;
}): ViolationType {
    return "other" in value ? ViolationType.other : "spam" in value ? ViolationType.spam : "harassment" in value ? ViolationType.harassment : "inappropriateContent" in value ? ViolationType.inappropriateContent : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    randomDebates: null;
} | {
    civilDebate: null;
} | {
    quotesPoems: null;
} | {
    aggressiveDebate: null;
}): SectionType {
    return "randomDebates" in value ? SectionType.randomDebates : "civilDebate" in value ? SectionType.civilDebate : "quotesPoems" in value ? SectionType.quotesPoems : "aggressiveDebate" in value ? SectionType.aggressiveDebate : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    reviewed: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "pending" in value ? ReportStatus.pending : "reviewed" in value ? ReportStatus.reviewed : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    post: bigint;
} | {
    userProfile: Principal;
} | {
    reply: bigint;
}): {
    __kind__: "post";
    post: bigint;
} | {
    __kind__: "userProfile";
    userProfile: Principal;
} | {
    __kind__: "reply";
    reply: bigint;
} {
    return "post" in value ? {
        __kind__: "post",
        post: value.post
    } : "userProfile" in value ? {
        __kind__: "userProfile",
        userProfile: value.userProfile
    } : "reply" in value ? {
        __kind__: "reply",
        reply: value.reply
    } : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModerationAction>): Array<ModerationAction> {
    return value.map((x)=>from_candid_ModerationAction_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n37(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n50(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n58(_uploadFile, _downloadFile, x));
}
function to_candid_AvatarColorChoice_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColorChoice): _AvatarColorChoice {
    return to_candid_record_n83(_uploadFile, _downloadFile, value);
}
function to_candid_AvatarColorType_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColorType): _AvatarColorType {
    return to_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function to_candid_AvatarCustomization_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarCustomization): _AvatarCustomization {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_AvatarStyleChoice_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarStyleChoice): _AvatarStyleChoice {
    return to_candid_record_n79(_uploadFile, _downloadFile, value);
}
function to_candid_AvatarStyleType_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarStyleType): _AvatarStyleType {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function to_candid_ConversationType_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConversationType): _ConversationType {
    return to_candid_variant_n87(_uploadFile, _downloadFile, value);
}
function to_candid_DebateStyle_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DebateStyle): _DebateStyle {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ModerationType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationType): _ModerationType {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function to_candid_ReportedContent_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportedContent): _ReportedContent {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_SectionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): _SectionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SocialMediaLinks_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaLinks): _SocialMediaLinks {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ViolationType_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ViolationType): _ViolationType {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    username: string;
    interests: Array<string>;
    socialMedia?: SocialMediaLinks;
    debateStyle: DebateStyle;
    avatar: AvatarCustomization;
}): {
    id: Principal;
    username: string;
    interests: Array<string>;
    socialMedia: [] | [_SocialMediaLinks];
    debateStyle: _DebateStyle;
    avatar: _AvatarCustomization;
} {
    return {
        id: value.id,
        username: value.username,
        interests: value.interests,
        socialMedia: value.socialMedia ? candid_some(to_candid_SocialMediaLinks_n72(_uploadFile, _downloadFile, value.socialMedia)) : candid_none(),
        debateStyle: to_candid_DebateStyle_n74(_uploadFile, _downloadFile, value.debateStyle),
        avatar: to_candid_AvatarCustomization_n76(_uploadFile, _downloadFile, value.avatar)
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitter?: string;
    instagram?: string;
    pinterest?: string;
    facebook?: string;
}): {
    twitter: [] | [string];
    instagram: [] | [string];
    pinterest: [] | [string];
    facebook: [] | [string];
} {
    return {
        twitter: value.twitter ? candid_some(value.twitter) : candid_none(),
        instagram: value.instagram ? candid_some(value.instagram) : candid_none(),
        pinterest: value.pinterest ? candid_some(value.pinterest) : candid_none(),
        facebook: value.facebook ? candid_some(value.facebook) : candid_none()
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing?: AvatarStyleChoice;
    eyewear?: AvatarStyleChoice;
    skinTone: AvatarColorChoice;
    hairType: AvatarStyleChoice;
}): {
    clothing: [] | [_AvatarStyleChoice];
    eyewear: [] | [_AvatarStyleChoice];
    skinTone: _AvatarColorChoice;
    hairType: _AvatarStyleChoice;
} {
    return {
        clothing: value.clothing ? candid_some(to_candid_AvatarStyleChoice_n78(_uploadFile, _downloadFile, value.clothing)) : candid_none(),
        eyewear: value.eyewear ? candid_some(to_candid_AvatarStyleChoice_n78(_uploadFile, _downloadFile, value.eyewear)) : candid_none(),
        skinTone: to_candid_AvatarColorChoice_n82(_uploadFile, _downloadFile, value.skinTone),
        hairType: to_candid_AvatarStyleChoice_n78(_uploadFile, _downloadFile, value.hairType)
    };
}
function to_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    styleType: AvatarStyleType;
}): {
    id: bigint;
    styleType: _AvatarStyleType;
} {
    return {
        id: value.id,
        styleType: to_candid_AvatarStyleType_n80(_uploadFile, _downloadFile, value.styleType)
    };
}
function to_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorType: AvatarColorType;
    colorId: bigint;
}): {
    colorType: _AvatarColorType;
    colorId: bigint;
} {
    return {
        colorType: to_candid_AvatarColorType_n84(_uploadFile, _downloadFile, value.colorType),
        colorId: value.colorId
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): {
    randomDebates: null;
} | {
    civilDebate: null;
} | {
    quotesPoems: null;
} | {
    aggressiveDebate: null;
} {
    return value == SectionType.randomDebates ? {
        randomDebates: null
    } : value == SectionType.civilDebate ? {
        civilDebate: null
    } : value == SectionType.quotesPoems ? {
        quotesPoems: null
    } : value == SectionType.aggressiveDebate ? {
        aggressiveDebate: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationType): {
    ban: null;
} | {
    warning: null;
} | {
    strike: null;
} {
    return value == ModerationType.ban ? {
        ban: null
    } : value == ModerationType.warning ? {
        warning: null
    } : value == ModerationType.strike ? {
        strike: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ViolationType): {
    other: null;
} | {
    spam: null;
} | {
    harassment: null;
} | {
    inappropriateContent: null;
} {
    return value == ViolationType.other ? {
        other: null
    } : value == ViolationType.spam ? {
        spam: null
    } : value == ViolationType.harassment ? {
        harassment: null
    } : value == ViolationType.inappropriateContent ? {
        inappropriateContent: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "post";
    post: bigint;
} | {
    __kind__: "userProfile";
    userProfile: Principal;
} | {
    __kind__: "reply";
    reply: bigint;
}): {
    post: bigint;
} | {
    userProfile: Principal;
} | {
    reply: bigint;
} {
    return value.__kind__ === "post" ? {
        post: value.post
    } : value.__kind__ === "userProfile" ? {
        userProfile: value.userProfile
    } : value.__kind__ === "reply" ? {
        reply: value.reply
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DebateStyle): {
    aggressive: null;
} | {
    creative: null;
} | {
    civil: null;
} | {
    random: null;
} {
    return value == DebateStyle.aggressive ? {
        aggressive: null
    } : value == DebateStyle.creative ? {
        creative: null
    } : value == DebateStyle.civil ? {
        civil: null
    } : value == DebateStyle.random ? {
        random: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarStyleType): {
    hat: null;
} | {
    wig: null;
} | {
    glasses: null;
} | {
    cape: null;
} | {
    hair: null;
} | {
    shirt: null;
} | {
    beard: null;
} {
    return value == AvatarStyleType.hat ? {
        hat: null
    } : value == AvatarStyleType.wig ? {
        wig: null
    } : value == AvatarStyleType.glasses ? {
        glasses: null
    } : value == AvatarStyleType.cape ? {
        cape: null
    } : value == AvatarStyleType.hair ? {
        hair: null
    } : value == AvatarStyleType.shirt ? {
        shirt: null
    } : value == AvatarStyleType.beard ? {
        beard: null
    } : value;
}
function to_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarColorType): {
    skinToneLevel: null;
} | {
    clothingColor: null;
} | {
    hairColor: null;
} {
    return value == AvatarColorType.skinToneLevel ? {
        skinToneLevel: null
    } : value == AvatarColorType.clothingColor ? {
        clothingColor: null
    } : value == AvatarColorType.hairColor ? {
        hairColor: null
    } : value;
}
function to_candid_variant_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConversationType): {
    group: null;
} | {
    direct: null;
} {
    return value == ConversationType.group ? {
        group: null
    } : value == ConversationType.direct ? {
        direct: null
    } : value;
}
function to_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    pending: null;
} | {
    reviewed: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.pending ? {
        pending: null
    } : value == ReportStatus.reviewed ? {
        reviewed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
